version: '3.0'

services:
  db:
    container_name: db
    image: postgres:latest
    volumes:
      - /var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=library_db
    ports:
      - 5432:5432
    
  backend:
    container_name: backend
    build:
      context: library_back/
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./library_back:/code
    ports:
      - 8000:8000
    depends_on:
      - db

  frontend:
    container_name: frontend
    build:
      context: library_front/
      dockerfile: Dockerfile
    volumes:
      - ./library_front:/app
    ports:
      - 3000:3000
    depends_on:
      - backend
      - db
    command: npm start

  nginx:
    build:
      context: nginx/
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db
      - backend
      - frontend

    