version: '3.0'

services:
  database:
    container_name: db
    image: postgres:latest
    restart: always
    volumes:
      - /var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=library_db
    ports:
      - 5432:5432